import { Component, OnInit } from '@angular/core';
import { listItem } from '../../module/list-item';

@Component({
  selector: 'app-list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.scss'],
})
export class ListItemComponent implements OnInit {
  cricketers: Array<listItem> = [
    // Indian Cricketers
    {
      name: 'Sachin Tendulkar',
      country: 'India',
      odiDebut: '18 December 1989',
      matches: 463,
      runs: 18426,
      highestScore: 200,
      centuries: 49,
      fifties: 96,
      battingAverage: 44.83,
      wickets: 154,
    },
    {
      name: 'Virat Kohli',
      country: 'India',
      odiDebut: '18 August 2008',
      matches: 292,
      runs: 13848,
      highestScore: 183,
      centuries: 50,
      fifties: 72,
      battingAverage: 58.67,
      wickets: 4,
    },
    {
      name: 'MS Dhoni',
      country: 'India',
      odiDebut: '23 December 2004',
      matches: 350,
      runs: 10773,
      highestScore: 183,
      centuries: 10,
      fifties: 73,
      battingAverage: 50.57,
      wickets: 1,
    },
    {
      name: 'Rohit Sharma',
      country: 'India',
      odiDebut: '23 June 2007',
      matches: 262,
      runs: 10709,
      highestScore: 264,
      centuries: 31,
      fifties: 55,
      battingAverage: 49.1,
      wickets: 10,
    },
    {
      name: 'Yuvraj Singh',
      country: 'India',
      odiDebut: '3 October 2000',
      matches: 304,
      runs: 8701,
      highestScore: 150,
      centuries: 14,
      fifties: 52,
      battingAverage: 36.56,
      wickets: 111,
    },
    {
      name: 'Sourav Ganguly',
      country: 'India',
      odiDebut: '11 January 1992',
      matches: 311,
      runs: 11363,
      highestScore: 183,
      centuries: 22,
      fifties: 72,
      battingAverage: 41.02,
      wickets: 100,
    },
    {
      name: 'Kapil Dev',
      country: 'India',
      odiDebut: '1 October 1978',
      matches: 225,
      runs: 3783,
      highestScore: 175,
      centuries: 1,
      fifties: 14,
      battingAverage: 23.79,
      wickets: 253,
    },
    {
      name: 'Rahul Dravid',
      country: 'India',
      odiDebut: '3 April 1996',
      matches: 344,
      runs: 10889,
      highestScore: 153,
      centuries: 12,
      fifties: 83,
      battingAverage: 39.16,
      wickets: 4,
    },
    {
      name: 'Virender Sehwag',
      country: 'India',
      odiDebut: '1 April 1999',
      matches: 251,
      runs: 8273,
      highestScore: 219,
      centuries: 15,
      fifties: 38,
      battingAverage: 35.05,
      wickets: 96,
    },

    // International Cricketers
    {
      name: 'Ricky Ponting',
      country: 'Australia',
      odiDebut: '15 February 1995',
      matches: 375,
      runs: 13704,
      highestScore: 164,
      centuries: 30,
      fifties: 82,
      battingAverage: 42.03,
      wickets: 3,
    },
    {
      name: 'AB de Villiers',
      country: 'South Africa',
      odiDebut: '2 February 2005',
      matches: 228,
      runs: 9577,
      highestScore: 176,
      centuries: 25,
      fifties: 53,
      battingAverage: 53.5,
      wickets: 7,
    },
    {
      name: 'Jacques Kallis',
      country: 'South Africa',
      odiDebut: '9 January 1996',
      matches: 328,
      runs: 11579,
      highestScore: 139,
      centuries: 17,
      fifties: 86,
      battingAverage: 44.36,
      wickets: 273,
    },
    {
      name: 'Chris Gayle',
      country: 'West Indies',
      odiDebut: '11 September 1999',
      matches: 301,
      runs: 10480,
      highestScore: 215,
      centuries: 25,
      fifties: 54,
      battingAverage: 37.83,
      wickets: 167,
    },

    {
      name: 'Brian Lara',
      country: 'West Indies',
      odiDebut: '9 November 1990',
      matches: 299,
      runs: 10405,
      highestScore: 169,
      centuries: 19,
      fifties: 63,
      battingAverage: 40.48,
      wickets: 4,
    },
    {
      name: 'Kane Williamson',
      country: 'New Zealand',
      odiDebut: '10 August 2010',
      matches: 161,
      runs: 6932,
      highestScore: 148,
      centuries: 13,
      fifties: 42,
      battingAverage: 47.6,
      wickets: 37,
    },
    {
      name: 'Ben Stokes',
      country: 'England',
      odiDebut: '25 August 2011',
      matches: 122,
      runs: 3491,
      highestScore: 182,
      centuries: 5,
      fifties: 22,
      battingAverage: 40.47,
      wickets: 74,
    },
  ];

  constructor() {}

  ngOnInit(): void {}
}
